[build]
  command = "pnpm run build"
  publish = "apps/web/dist"
  functions = "functions"

[dev]
  command = "pnpm dev"
  framework = "#auto"
  publish = "apps/web/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
