[build]
  command = "pnpm run build"
  publish = "apps/web/dist"
  functions = "functions"

[dev]
  command = "turbo run dev --filter web"
  framework = "#auto"
  publish = "apps/web/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
